# Generated by Django 4.2.18 on 2025-04-24 11:37

from django.db import migrations, models

class Migration(migrations.Migration):
    atomic = False  # Added to support concurrent index creation
    dependencies = [
        ("posthog", "0716_backfill_team_revenue_analytics_config"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="errortrackingassignmentrule",
                    name="role_id",
                    field=models.UUIDField(blank=True, db_index=True, null=True),
                ),
                migrations.AddField(
                    model_name="errortrackingissueassignment",
                    name="role_id",
                    field=models.UUIDField(blank=True, db_index=True, null=True),
                ),
            ],
            database_operations=[
                # We add -- existing-table-constraint-ignore to ignore the constraint validation in CI.
                migrations.RunSQL(
                    """
                    ALTER TABLE "posthog_errortrackingassignmentrule" ADD COLUMN IF NOT EXISTS "role_id" uuid NULL;
                    """,
                    reverse_sql="""
                        ALTER TABLE "posthog_errortrackingassignmentrule" DROP COLUMN IF EXISTS "role_id";
                    """,
                ),
                migrations.RunSQL(
                    """
                    ALTER TABLE "posthog_errortrackingissueassignment" ADD COLUMN IF NOT EXISTS "role_id" uuid NULL;
                    """,
                    reverse_sql="""
                        ALTER TABLE "posthog_errortrackingissueassignment" DROP COLUMN IF EXISTS "role_id";
                    """,
                ),
                # We add CONCURRENTLY to the create command
                migrations.RunSQL(
                    """
                    CREATE INDEX CONCURRENTLY "posthog_errortrackingassignmentrule_role_id_5faac145" ON "posthog_errortrackingassignmentrule" ("role_id");
                    """,
                    reverse_sql="""
                        DROP INDEX IF EXISTS "posthog_errortrackingassignmentrule_role_id_5faac145";
                    """,
                ),
                migrations.RunSQL(
                    """
                    CREATE INDEX CONCURRENTLY "posthog_errortrackingissueassignment_role_id_f84c52d3" ON "posthog_errortrackingissueassignment" ("role_id");
                    """,
                    reverse_sql="""
                        DROP INDEX IF EXISTS "posthog_errortrackingissueassignment_role_id_f84c52d3";
                    """,
                ),
            ],
        ),
    ]
