# Generated by Django 4.2.22 on 2025-08-20 19:39

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False  # Added to support concurrent index creation
    dependencies = [
        ("posthog", "0828_grouptypemapping_created_at"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="organization",
                    name="default_role_id",
                    field=models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="Role automatically assigned to new members joining the organization when EE is available.",
                        null=True,
                    ),
                ),
            ],
            database_operations=[
                # We add -- existing-table-constraint-ignore to ignore the constraint validation in CI.
                migrations.RunSQL(
                    """
                    ALTER TABLE "posthog_organization" ADD COLUMN IF NOT EXISTS "default_role_id" uuid NULL;
                    """,
                    reverse_sql="""
                        ALTER TABLE "posthog_organization" DROP COLUMN IF EXISTS "default_role_id";
                    """,
                ),
                # We add CONCURRENTLY to the create command
                migrations.RunSQL(
                    """
                    CREATE INDEX CONCURRENTLY "posthog_organization_default_role_id_03bcd28b" ON "posthog_organization" ("default_role_id");
                    """,
                    reverse_sql="""
                        DROP INDEX IF EXISTS "posthog_organization_default_role_id_03bcd28b";
                    """,
                ),
            ],
        )
    ]
